dist: trusty
sudo: require

compiler: gcc
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - gcc-8
      - g++-8
      - cmake
      - git
      - make

jobs:
  include:
    - stage: Unit Tests
      script:
        - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
        - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++

        - export CC=/usr/bin/gcc-8
        - export CXX=/usr/bin/g++-8

        - sudo apt-get install -y git g++ make cmake
        - git clone https://github.com/google/googletest.git
        - cd googletest
        - mkdir gbuild && cd gbuild && cmake .. && make
        - cp -r googletest/include/gtest /usr/local/include
        - cp gbuild/googlemock/gtest/lib*.a /usr/local/lib
        - cp gbuild/googlemock/lib*.a /usr/local/lib
        - make tests

    - stage: Memory Check
      script:
        - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
        - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++

        - sudo apt-get install valgrind

        - export CC=/usr/bin/gcc-8
        - export CXX=/usr/bin/g++-8

        - sudo apt-get install googletest

        - make mem_check
